const numero = "51920726588";let carrito = [];
const precios = {"spam_3d": {PE:"S/5.50", CL:"$1750", AR:"$2600", MX:"$37.5", BO:"Bs22.5", UY:"$75"},"spam_5d": {PE:"S/7.50", CL:"$2450", AR:"$3640", MX:"$52.5", BO:"Bs31.5", UY:"$105"},"spam_7d": {PE:"S/9.50", CL:"$3150", AR:"$4680", MX:"$67.5", BO:"Bs40.5", UY:"$135"},"d110c": {PE:"S/2.50", CL:"$875", AR:"$1300", MX:"$18.75", BO:"Bs11.25", UY:"$37.5"},"d341c": {PE:"S/7.00", CL:"$2450", AR:"$3380", MX:"$52.50", BO:"Bs31.5", UY:"$105"},"d572c": {PE:"S/12.00", CL:"$4200", AR:"$5720", MX:"$90", BO:"Bs54", UY:"$180"},"d1166c":{PE:"S/20.00", CL:"$7000", AR:"$9880", MX:"$150", BO:"Bs90", UY:"$300"},"d2398c":{PE:"S/36.00", CL:"$12600", AR:"$18200", MX:"$270", BO:"Bs162", UY:"$540"},"d6160c":{PE:"S/92.00", CL:"$32200", AR:"$46800", MX:"$690", BO:"Bs414", UY:"$1380"},"d110s": {PE:"S/3.50", CL:"$1225", AR:"$1820", MX:"$26.25", BO:"Bs15.75", UY:"$52.5"},"d341s": {PE:"S/10.00", CL:"$3500", AR:"$4680", MX:"$75", BO:"Bs45", UY:"$150"},"d572s": {PE:"S/15.00", CL:"$5250", AR:"$7800", MX:"$112.5", BO:"Bs67.5", UY:"$225"},"d1166s":{PE:"S/26.00", CL:"$9100", AR:"$13520", MX:"$195", BO:"Bs117", UY:"$390"},"d2398s":{PE:"S/52.00", CL:"$18200", AR:"$27040", MX:"$390", BO:"Bs234", UY:"$780"},"d6160s":{PE:"S/126.00", CL:"$44100", AR:"$65520", MX:"$945", BO:"Bs567", UY:"$1890"},"logo": {PE:"S/3", CL:"$1050", AR:"$1560", MX:"$22.5", BO:"Bs13.5", UY:"$22.5"},"plantilla":{PE:"S/4", CL:"$1050", AR:"$1560", MX:"$22.5", BO:"Bs13.5", UY:"$22.5"},"caligra":{PE:"S/3", CL:"$1050", AR:"$1560", MX:"$22.5", BO:"Bs13.5", UY:"$22.5"},"jersey": {PE:"S/5", CL:"$1750", AR:"$2600", MX:"$37.5", BO:"Bs22.5", UY:"$75"},"decana": {PE:"S/15", CL:"$5000", AR:"$7000", MX:"$114", BO:"Bs55.5", UY:"$210"},"seg_250": {PE:"S/1.50", CL:"$525", AR:"$520", MX:"$11.25", BO:"Bs6.75", UY:"$22.5"},"seg_500": {PE:"S/2.50", CL:"$875", AR:"$1040", MX:"$18.75", BO:"Bs11.25",UY:"$37.5"},"seg_1000": {PE:"S/5", CL:"$1750", AR:"$2080", MX:"$37.5", BO:"Bs22.5", UY:"$75"},"seg_2000": {PE:"S/10", CL:"$3500", AR:"$4680", MX:"$75", BO:"Bs45", UY:"$150"},"seg_5000": {PE:"S/20", CL:"$7000", AR:"$9360", MX:"$150", BO:"Bs90", UY:"$300"},}
const descripciones = {"spam_3d": "3 días de spam. 3 horas por día. Puro texto.","spam_5d": "5 días de spam. 3 horas por día. Puro texto.","spam_7d": "7 días de spam. 3 horas por día. Puro texto.","d110c": "110 Diamantes CON STOCK. Recarga rápida.","d341c": "341 Diamantes CON STOCK. Recarga rápida.","d572c": "572 Diamantes CON STOCK. Recarga rápida.","d1166c":"1166 Diamantes CON STOCK. Recarga rápida.","d2398c":"2398 Diamantes CON STOCK. Recarga rápida.","d6160c":"6160 Diamantes CON STOCK. Recarga rápida.","d110s": "110 Diamantes SIN STOCK. Puede demorar.","d341s": "341 Diamantes SIN STOCK. Puede demorar.","d572s": "572 Diamantes SIN STOCK. Puede demorar.","d1166s":"1166 Diamantes SIN STOCK. Puede demorar.","d2398s":"2398 Diamantes SIN STOCK. Puede demorar.","d6160s":"6160 Diamantes SIN STOCK. Puede demorar.","logo": "Logo o Tex Logo personalizado. Entrega en 2 días.","plantilla":"Plantillas 2x1. Diseños para clanes.","caligra":"Caligráficos 2x1. Nombres bonitos.","jersey": "Diseño de Jersey para clan.","decana": "Combo Decana Semanal: Vs + Reclutamiento + Edición.","seg_250": "250 Seguidores Instagram. Entrega segura.","seg_500": "500 Seguidores Instagram. Entrega segura.","seg_1000": "1000 Seguidores Instagram. Entrega segura.","seg_2000": "2000 Seguidores Instagram. Entrega segura.","seg_5000": "5000 Seguidores Instagram. Entrega segura.",}
const productosData = [{cat:"📢 SPAM 3H x DÍA", items:["spam_3d","spam_5d","spam_7d"]},{cat:"💎 DIAMANTES CON STOCK", items:["d110c","d341c","d572c","d1166c","d2398c","d6160c"]},{cat:"💎 DIAMANTES SIN STOCK", items:["d110s","d341s","d572s","d1166s","d2398s","d6160s"]},{cat:"🖌️ LUU DESIGN", items:["logo","plantilla","caligra","jersey"]},{cat:"🎀 COMBO DECANA LUU", items:["decana"]},{cat:"📈 SEGUIDORES IG", items:["seg_250","seg_500","seg_1000","seg_2000","seg_5000"]}]
function toggleMenu(){ let menu = document.getElementById("menu"); if(menu) menu.classList.toggle("active"); }
function guardarCarrito(){ localStorage.setItem("carritoGarfield", JSON.stringify(carrito)); }
function cargarCarritoGuardado(){ let guardado = localStorage.getItem("carritoGarfield"); if(guardado) carrito = JSON.parse(guardado); }
function actualizarMenuTotal(){ let el = document.getElementById("menuTotal"); if(el) el.innerText = carrito.length; }
let prodSeleccionado = {};
function cargarProductos(){if(!document.getElementById("productos")) return;let html = "";productosData.forEach(cat=>{html += `<h2 style="padding:20px 0 10px; color:#ff0040; font-size:20px;">${cat.cat}</h2>`;cat.items.forEach(id=>{let nombre = id.replace(/_/g,' ').toUpperCase();html += `<div class="prod-card-cyber" onclick="abrirOpciones('${id}','${nombre}')"><h3>> ${nombre}</h3><div class="prod-precio-cyber" data-precio="${id}">CARGANDO...</div><p style="font-size:12px; color:#aaa; margin-top:8px;">[CLICK PARA OPCIONES]</p></div>`;});document.getElementById("productos").innerHTML = html;cambiarPrecios();}
function abrirOpciones(id, nombre){prodSeleccionado = {id, nombre};let pais = document.getElementById("pais").value;let precio = precios[id][pais];let desc = descripciones[id];document.getElementById("popupOpciones").innerHTML = `<div class="popup-content"><h3>> ${nombre}</h3><p style="color:#ff0040; font-size:24px; font-weight:900; margin:10px 0;">${precio}</p><p style="font-size:14px; color:#ccc; margin:10px 0;">${desc}</p><button class="btn-add-cyber" onclick="confirmarAgregar()">[AÑADIR AL CARRITO]</button><button onclick="cerrarOpciones()" class="btn-cerrar">CERRAR</button></div>`;document.getElementById("popupOpciones").style.display = "flex";}
function cerrarOpciones(){ document.getElementById("popupOpciones").style.display = "none"; }
function confirmarAgregar(){let pais = document.getElementById("pais").value;let precio = precios[prodSeleccionado.id][pais];if(prodSeleccionado.id.includes('s') && prodSeleccionado.id.startsWith('d')){if(!confirm(`[ALERTA] ${prodSeleccionado.nombre} SIN STOCK\n¿Añadir igual?`)) return;}carrito.push({nombre: prodSeleccionado.nombre, precio, id: prodSeleccionado.id});guardarCarrito();actualizarCarrito();actualizarMenuTotal();alert(`[OK] ${prodSeleccionado.nombre} AÑADIDO`);cerrarOpciones();}
function buscarProducto(){let filtro = document.getElementById("buscador").value.toLowerCase();document.querySelectorAll(".prod-card-cyber").forEach(p=>{let texto = p.innerText.toLowerCase();p.style.display = texto.includes(filtro)? 'block' : 'none';})}
function toggleMusica(){let audio = document.getElementById("musicaFondo");let btn = document.getElementById("btnMusica");if(!audio ||!btn) return; if(audio.paused){ audio.play().catch(e=>{}); btn.innerText = "🔇 PAUSA"; }else { audio.pause(); btn.innerText = "🔊 AUDIO"; }}
function cambiarPrecios(){let pais = document.getElementById("pais").value;document.querySelectorAll("[data-precio]").forEach(el=>{let id = el.getAttribute("data-precio");el.innerText = precios[id][pais];})localStorage.setItem("paisGarfield", pais);}
function actualizarCarrito(){let el = document.getElementById("totalItems"); if(el) el.innerText = carrito.length;let html = "";carrito.forEach((item)=>{let tag = item.id.includes('s') && item.id.startsWith('d')? ' [SIN STOCK]' : ' [CON STOCK]';html += `<p style="border-bottom:1px solid #ff004022; padding:12px 0; font-size:16px; color:#fff;">> ${item.nombre}${tag} :: ${item.precio}</p>`;});let lista = document.getElementById("listaCarrito"); if(lista) lista.innerHTML = html || "<p style='color:#ccc'>> CARRITO VACIO</p>";}
function abrirPopUpID(){if(carrito.length === 0) return alert("[ERROR] CARRITO VACIO");document.getElementById("popupID").style.display = "flex";}
function cerrarPopUpID(){ document.getElementById("popupID").style.display = "none"; }
function enviarWhatsApp(){let id = document.getElementById("idFinal").value;if(!id) return alert("[ERROR] INGRESA TU ID");let pais = localStorage.getItem("paisGarfield") || "PE";let texto = `HOLA GARFIELD STORE\nPAIS: ${pais}\nID: ${id}\n\nPEDIDO:\n`;carrito.forEach(item=>{let tag = item.id.includes('s') && item.id.startsWith('d')? ' [SIN STOCK]' : ' [CON STOCK]';texto += `- ${item.nombre}${tag}: ${item.precio}\n`});window.open(`https://wa.me/${numero}?text=${encodeURIComponent(texto)}`,"_blank");carrito = [];guardarCarrito();actualizarCarrito();actualizarMenuTotal();cerrarPopUpID();}
document.addEventListener('DOMContentLoaded', ()=>{cargarCarritoGuardado();actualizarMenuTotal();actualizarCarrito();if(document.getElementById("pais")){let paisGuardado = localStorage.getItem("paisGarfield") || "PE";document.getElementById("pais").value = paisGuardado;}if(document.getElementById("productos")) cargarProductos();let audio = document.getElementById("musicaFondo"); if(audio) audio.volume = 0.3;});